env:
  TERM: alacritty

window:
  dynamic_padding: true
  decorations: buttonless


font:
  normal:
    family: InconsolataGo Nerd Font
    style: Regular

  size: 20

import:
  - ~/.config/alacritty/themes/onedark.yml

key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Return, mods: Command, action: ToggleFullscreen }
