# sops-nix configuration
# Secrets are encrypted with age keys defined here

keys:
  # dosvec server
  - &dosvec age1k86acr23u57gppgvuawe6usssm9njurknzdjue2lstuvscg4uakqkcu7p6

creation_rules:
  # NixOS system secrets for dosvec
  - path_regex: secrets/dosvec\.enc\.yaml$
    key_groups:
      - age:
          - *dosvec
