# vim: ft=zsh
#

# Borrowed from: https://kev.inburke.com/kevin/profiling-zsh-startup-time/
PROFILE_STARTUP=false

if [[ "$PROFILE_STARTUP" == true ]]; then
    # http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
    mkdir $HOME/tmp
    PS4=$'%D{%M%S%.} %N:%i> '
    exec 3>&2 2>$HOME/tmp/startlog.$$
    setopt xtrace prompt_subst
fi

# LOCAL VARIABLES
DISABLE_AUTO_TITLE="true"

# This is commented out because git aliases
# won't autocomplete unless this isn't set.
# Shit's broke: https://github.com/robbyrussell/oh-my-zsh/issues/4407
# setopt completealiases

# source the base zshrc configurations first
for config_file in ~/.config/zsh/*.zsh(N); do source $config_file; done

# source the remaining zsh config files
for config_file in ~/.config/^zsh/*.zsh(N); do source $config_file; done

# Use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
# This must be last so these settings overwrite anything
# previously set.
if [[ -a ~/.localrc ]]; then
  source ~/.localrc
fi

if [[ "$PROFILE_STARTUP" == true ]]; then
    unsetopt xtrace
    exec 2>&3 3>&-
fi
