return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  event = { "BufReadPost", "BufNewFile" },
  cmd = { "TSInstall" },
  build = ":TSUpdate",
  config = function()
    pcall(function()
      dofile(vim.g.base46_cache .. "syntax")
      dofile(vim.g.base46_cache .. "treesitter")
    end)

    require("nvim-treesitter").install({
      "bash",
      "blade",
      "c",
      "css",
      "diff",
      "dockerfile",
      "ecma",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "hcl",
      "helm",
      "html",
      "html_tags",
      "javascript",
      "latex",
      "lua",
      "luadoc",
      "nix",
      "php",
      "php_only",
      "printf",
      "python",
      "regex",
      "ruby",
      "rust",
      "scss",
      "sql",
      "ssh_config",
      "svelte",
      "swift",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "typst",
      "vim",
      "vimdoc",
      "vue",
      "yaml",
    })
  end,
}
