#!/usr/bin/env zsh

set +e

if ! command -v cargo > /dev/null; then
  echo "Installing Rustup"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
else
  echo "Rustup already installed"
fi

set -e
