#!/usr/bin/env zsh

. "$(dirname $0)/colors"
. "$(dirname $0)/apt-install"
. ./tag-zsh/config/zsh/functions/host_os_is_linux
. ./tag-zsh/config/zsh/functions/host_os_is_macos
. ./tag-zsh/config/zsh/functions/host_os_is_arm

. ./rcrc

if host_os_is_macos; then
  ./setup/install-homebrew

  if host_os_is_arm; then
    softwareupdate --install-rosetta --agree-to-license
  fi
fi

./setup/install-rustup
./setup/link-dotfiles

set -x
setopt extendedglob

# Check for presence of additional setup files
# keeping tags in mind
if [[ -n *tag-*/setup/*(#qN) ]]; then
  # Source additional setup files
  for file in tag-*/setup/*; do
    TAG_NAME=`echo $file | awk -F'/' '{print $1}' | awk -F'-' '{print $2}'`

    echo $TAGS | grep -q $TAG_NAME
    TAG_INCLUDED=$?

    if [ $TAG_INCLUDED -eq 0 ]; then
      source "$file"
    fi
  done
fi

if host_os_is_linux && [[ -z ${DOCKER+1} ]]; then
  do_apt_install
else
  echo "We are in a dockerized context, not doing any package installation via apt"
fi
